### ISSUE TITLE
BUG Backspace Adds Link Content when Editing Profile Social Links

### ISSUE THREAD

**Issue by hughgramel** [swecc-uw/swecc-website#116]
**Describe the bug**
When editing profile information under "Social Links," pressing the backspace key within the input fields when it's empty causes the field to autofill with part of the URL's content (e.g., /in, /github.com, or /u) from the respective links.
**To Reproduce**

1. Navigate to the "Edit Profile" section.
2. Go to the "Social Links" tab.
3. Click into any social link input field (e.g., LinkedIn, GitHub, LeetCode) that's empty.
4. Press the backspace key.
5. Observe that part of the URL (e.g., /in, /github.com, or /u) appears in the input field.
(after pressing, now "https://github.com/github.com" or "https://leetcode.com/u/u")

**Expected behavior**
Pressing backspace with no content in the input field should do nothing

**Details (please complete the following information):**

- Macbook air
- Chrome

**Comment by elimelt** [comment]
Thanks for submitting an issue! Looks like this is meant for https://github.com/swecc-uw/swecc-client though

**Comment by hughgramel** [comment]
Okay I'll post it there, thanks!
