### ISSUE TITLE
BUG Slash Key Deletes Content when Editing Profile Social Links

### ISSUE THREAD

**Issue by hughgramel** [swecc-uw/swecc-website#117]
**Describe the bug**
Typing the / character in any social link input field results in the deletion of existing text within the field.

**To Reproduce**

1. Navigate to the "Edit Profile" section.
2. Go to the "Social Links" tab.
3. Click into any social link input field (e.g., LinkedIn, GitHub, LeetCode).
4. Type the / character.
5. Observe that the text in the input field gets deleted.

**Expected behavior**
Typing / should add the character to the input field without affecting other text.

**Details (please complete the following information):**

- Macbook air [e.g. Desktop, Smartphone]
- Chrome [e.g. chrome, safari]

**Comment by elimelt** [comment]
Thanks for the detailed description! It looks like this issue was meant for https://github.com/swecc-uw/swecc-client

**Comment by elimelt** [comment]
Closing here but will start working on fix, feel free to open issue in the correct repository if you want it tagged in the fix
