### ISSUE TITLE
BUG: Out of date information

### ISSUE THREAD

**Issue by shiinasugioka** [swecc-uw/swecc-website#34]
**Describe the bug**
In the homepage, the meeting details are out of date.

**Expected behavior**
* Meetings are not held in the EAC, they are held at Loew 216.
* Meeting times should be labelled for Spring 2024

**Screenshots**
![image](https://github.com/swecc-uw/swecc-website/assets/91639423/ec563592-2dfd-4932-abc0-74065e3c01ca)

**Comment by FLinLan** [comment]
Currently Assigned to this issue

**Comment by shiinasugioka** [comment]
@FLinLan assigned
