### ISSUE TITLE
Hyperlink 'Dubvelopers' on bottom of page

### ISSUE THREAD

**Issue by deeksha-vatwani** [swecc-uw/swecc-website#44]
On the bottom left part of the website, we have a small message that reads 'Collaboration with Dubvelopers'. Hyperlink the text 'Dubvelopers' with a link to Dubvelopers' website
<img width="1606" alt="Screenshot 2024-04-01 at 7 28 22 PM" src="https://github.com/swecc-uw/swecc-website/assets/150943110/27492e5d-8970-4815-bbb3-bfce3c724eca">

**Comment by mathlord2** [comment]
Actually, DUBvelopers renamed themselves to **"Web Impact UW"** so use that name instead!

**Comment by cjohn444** [comment]
Hi, I'd like to take this issue @shiinasugioka

**Comment by shiinasugioka** [comment]
@cjohn444 Assigned!
