### ISSUE TITLE
Don't spam the dark mode switch

### ISSUE THREAD

**Issue by wkxdavid** [swecc-uw/swecc-website#45]
**Is your feature request related to a problem? Please describe.**
This is an fun feature. There is no direct bug or issue, just a fun game easter egg.

**Describe the solution you'd like**
When the dark and light mode switch has been clicked 10 times, display a small pop up message that makes a joke.

**Additional context**
The joke can be anything or it can cycle. Potentially, if you keep clicking it after the message, it will start getting more annoyed or mad? May need design depending on how and where the message will be displayed.
![image](https://github.com/swecc-uw/swecc-website/assets/98622436/025d735d-bde1-4cee-abab-33a6a2e42314)

**Comment by shiinasugioka** [comment]
@RandolphTang Assigned! Also my github is @shiinasugioka haha

**Comment by RandolphTang** [comment]
@shiinasugioka 
hello Shiina, I also finished the Don't spam the dark mode switch issue, and the new commit is called "Don't spam the dark mode switch 4/13." I don't know why the page always directs me to the front page background image issue when I open pull request, so just letting you know here.

**Comment by shiinasugioka** [comment]
@RandolphTang Thank you, I’ll take a look by the end of the day. Feel free to pick up new issues while you wait

**Comment by shiinasugioka** [comment]
@RandolphTang Can you share a link to the PR? I don't see it

**Comment by RandolphTang** [comment]
@shiinasugioka Oh I think it was accidentally committed to the front page title pull request 
https://github.com/swecc-uw/swecc-website/pull/88#pullrequestreview-1999339859
(the last 3 commit were the Don't spam the dark mode switch)

Sorry for the inconvenience.

**Comment by shiinasugioka** [comment]
@RandolphTang Oh I see what happened. I recommend you use a different branch for each issue you're working on. The pull request merged changed from your Don't spam issue as well as both the issues were on the main branch. That's my bad for not noticing, but it also looks like the dark mode switch is working fine. Great job!
