### ISSUE TITLE
Normalize format of officer names

### ISSUE THREAD

**Issue by deeksha-vatwani** [swecc-uw/swecc-website#46]
**Describe the bug**
Under the 'officers' page, some officers have their full name listed, while others only have their first. For the sake of consistency, edit this page such that all officers' full names are listed.

**Details (please complete the following information):**
Names:
Shiina Sugioka
Deeksha Vatwani
Ruhee Rajwani
Trang Tran
Aditya Khowal
Leah Jia
Eric Xiao
Aditya Akhileshwaran
Elijah Melton
David Pham
Daniel Bejar
Bhavya Linga

Past officers:
Eyad Alsilimy
Hawa Drammeh
Simon Studen

**Comment by rina-reimer** [comment]
@shiinasugioka I would like to work on this issue

**Comment by shiinasugioka** [comment]
@rina-reimer Assigned!
