### ISSUE TITLE
BUG: Board Members page header is out of date

### ISSUE THREAD

**Issue by shiinasugioka** [swecc-uw/swecc-website#54]
**Describe the bug**
The heading for the Board Members page is out of date. Instead of "About Us", the page header should introduce the "Board Members" page.

**Expected behavior**
Heading: "SWECC Officers"
Description: "Learn about the team behind SWECC."

**Screenshots**
<img width="1350" alt="image" src="https://github.com/swecc-uw/swecc-website/assets/91639423/7a98e1d6-2913-4816-aea9-400b68b7c1b1">

**Comment by acao08** [comment]
@shiinasugioka I want to work on this issue.

**Comment by shiinasugioka** [comment]
@acao08 Assigned!
