### ISSUE TITLE
Update Front page

### ISSUE THREAD

**Issue by AdityaKhowalGithub** [swecc-uw/swecc-website#59]
Update front page, add in a carosel of picture from swecc meetings and relocate SWECC text.

<img width="1685" alt="image" src="https://github.com/swecc-uw/swecc-website/assets/108611217/4f297af2-c3fe-4ff6-8ca6-ea1599553d36">

Update this part to be a carousel, get pictures from Instagram

**Comment by realjero** [comment]
Is this issue still unresolved? I'm interested in addressing it. Regarding the issue, I propose enabling automatic scrolling through the carousel images. Additionally, would you prefer to include pagination for users to manually select images? Also, could you specify the desired position for the SWECC text? Is it possible to provide a link to your Instagram images as well? This could help in integrating them into the carousel.

**Comment by RandolphTang** [comment]
hello, I just wonder if this issue still unresolved, I would be love to help with it. @shiinasugi

**Comment by shiinasugioka** [comment]
@RandolphTang Assigned!

**Comment by shiinasugioka** [comment]
> Is this issue still unresolved? I'm interested in addressing it. Regarding the issue, I propose enabling automatic scrolling through the carousel images. Additionally, would you prefer to include pagination for users to manually select images? Also, could you specify the desired position for the SWECC text? Is it possible to provide a link to your Instagram images as well? This could help in integrating them into the carousel.

Hi @realjero , we are a college organization. Our issues are reserved for our members for the next two weeks. If no one has finished this issue by the end of the month then I can take a look at your PR. Thank you
