### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by mathlord2** [swecc-uw/swecc-website#91]
**Describe the bug**
On dark mode, the purple header text becomes harder to read.

**To Reproduce**
Open swecc.org and toggle dark mode on.

**Expected behavior**
Text or background should be brighter to increase the contrast.

**Screenshots**
![image](https://github.com/swecc-uw/swecc-website/assets/42785168/ef134b36-413f-41f6-b804-5386f12626ff)

**Details (please complete the following information):**
 - Device: all
 - Browser: all

**Additional context**
N/A

**Comment by shiinasugioka** [comment]
duplicate issue, resolving because this came later. Thanks!
